### ISSUE TITLE
Unquoted column names in updatable_l10_view trigger

### ISSUE THREAD

**Issue by alxarch** [bigsmoke/pg_xenophile#2]
There are two occurrences of unquoted column names used in dynamic queries in `updatable_l10_view` trigger.
Column names from `information_schema.columns` can be arbitrary strings that can break the resulting SQL.
I think that both occurrences of `array_to_string` should be replaced with 
```sql
(SELECT string_agg( quote_ident(col), ',') FROM unnest(_XXX_columns_to_upsert) as col)
```
to avoid problems with 'exotic' column names.

https://github.com/bigsmoke/pg_xenophile/blob/6af85ff0ff0cf70eb6b5f5c60db669a0664c8d65/sql/pg_xenophile--0.5.0.sql#L1133

https://github.com/bigsmoke/pg_xenophile/blob/6af85ff0ff0cf70eb6b5f5c60db669a0664c8d65/sql/pg_xenophile--0.5.0.sql#L1093

**Comment by bigsmoke** [comment]
Thanks a lot for reporting this oversight. I just pushed version 0.5.4 which fixes this issue.

**Comment by bigsmoke** [comment]
Before fixing the trigger function, I changed the test case to require quoting for both a column in the base table and a column in the l10n table.
